// This file is auto-generated by @hey-api/openapi-ts

import { type InfiniteData, infiniteQueryOptions, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { getApiFacebookAccounts, getApiFacebookChats, getApiFacebookChatsById, getApiFacebookImports, getApiFacebookMessages, getApiFacebookMessagesByChatId, type Options, postApiFacebookImports } from '../sdk.gen';
import type { GetApiFacebookAccountsData, GetApiFacebookChatsByIdData, GetApiFacebookChatsData, GetApiFacebookImportsData, GetApiFacebookMessagesByChatIdData, GetApiFacebookMessagesByChatIdError, GetApiFacebookMessagesByChatIdResponse, GetApiFacebookMessagesData, PostApiFacebookImportsData, PostApiFacebookImportsError, PostApiFacebookImportsResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [
        params
    ];
};

export const getApiFacebookAccountsQueryKey = (options?: Options<GetApiFacebookAccountsData>) => createQueryKey('getApiFacebookAccounts', options);

/**
 * Get API facebook accounts
 */
export const getApiFacebookAccountsOptions = (options?: Options<GetApiFacebookAccountsData>) => queryOptions({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiFacebookAccounts({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiFacebookAccountsQueryKey(options)
});

export const getApiFacebookChatsQueryKey = (options?: Options<GetApiFacebookChatsData>) => createQueryKey('getApiFacebookChats', options);

/**
 * Get API facebook chats
 */
export const getApiFacebookChatsOptions = (options?: Options<GetApiFacebookChatsData>) => queryOptions({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiFacebookChats({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiFacebookChatsQueryKey(options)
});

export const getApiFacebookChatsByIdQueryKey = (options: Options<GetApiFacebookChatsByIdData>) => createQueryKey('getApiFacebookChatsById', options);

/**
 * Get API facebook chats by ID
 */
export const getApiFacebookChatsByIdOptions = (options: Options<GetApiFacebookChatsByIdData>) => queryOptions({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiFacebookChatsById({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiFacebookChatsByIdQueryKey(options)
});

export const getApiFacebookImportsQueryKey = (options?: Options<GetApiFacebookImportsData>) => createQueryKey('getApiFacebookImports', options);

/**
 * Get API facebook imports
 */
export const getApiFacebookImportsOptions = (options?: Options<GetApiFacebookImportsData>) => queryOptions({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiFacebookImports({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiFacebookImportsQueryKey(options)
});

/**
 * Post API facebook imports
 */
export const postApiFacebookImportsMutation = (options?: Partial<Options<PostApiFacebookImportsData>>): UseMutationOptions<PostApiFacebookImportsResponse, PostApiFacebookImportsError, Options<PostApiFacebookImportsData>> => {
    const mutationOptions: UseMutationOptions<PostApiFacebookImportsResponse, PostApiFacebookImportsError, Options<PostApiFacebookImportsData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postApiFacebookImports({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getApiFacebookMessagesQueryKey = (options?: Options<GetApiFacebookMessagesData>) => createQueryKey('getApiFacebookMessages', options);

/**
 * Get API facebook messages
 */
export const getApiFacebookMessagesOptions = (options?: Options<GetApiFacebookMessagesData>) => queryOptions({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiFacebookMessages({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiFacebookMessagesQueryKey(options)
});

export const getApiFacebookMessagesByChatIdQueryKey = (options: Options<GetApiFacebookMessagesByChatIdData>) => createQueryKey('getApiFacebookMessagesByChatId', options);

/**
 * Get API facebook messages by chat ID
 */
export const getApiFacebookMessagesByChatIdOptions = (options: Options<GetApiFacebookMessagesByChatIdData>) => queryOptions({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiFacebookMessagesByChatId({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiFacebookMessagesByChatIdQueryKey(options)
});

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>>(queryKey: QueryKey<Options>, page: K) => {
    const params = {
        ...queryKey[0]
    };
    if (page.body) {
        params.body = {
            ...queryKey[0].body as any,
            ...page.body as any
        };
    }
    if (page.headers) {
        params.headers = {
            ...queryKey[0].headers,
            ...page.headers
        };
    }
    if (page.path) {
        params.path = {
            ...queryKey[0].path as any,
            ...page.path as any
        };
    }
    if (page.query) {
        params.query = {
            ...queryKey[0].query as any,
            ...page.query as any
        };
    }
    return params as unknown as typeof page;
};

export const getApiFacebookMessagesByChatIdInfiniteQueryKey = (options: Options<GetApiFacebookMessagesByChatIdData>): QueryKey<Options<GetApiFacebookMessagesByChatIdData>> => createQueryKey('getApiFacebookMessagesByChatId', options, true);

/**
 * Get API facebook messages by chat ID
 */
export const getApiFacebookMessagesByChatIdInfiniteOptions = (options: Options<GetApiFacebookMessagesByChatIdData>) => {
    return infiniteQueryOptions<GetApiFacebookMessagesByChatIdResponse, GetApiFacebookMessagesByChatIdError, InfiniteData<GetApiFacebookMessagesByChatIdResponse>, QueryKey<Options<GetApiFacebookMessagesByChatIdData>>, number | Pick<QueryKey<Options<GetApiFacebookMessagesByChatIdData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
    // @ts-ignore
    {
        queryFn: async ({ pageParam, queryKey, signal }) => {
            // @ts-ignore
            const page: Pick<QueryKey<Options<GetApiFacebookMessagesByChatIdData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
                query: {
                    page: pageParam
                }
            };
            const params = createInfiniteParams(queryKey, page);
            const { data } = await getApiFacebookMessagesByChatId({
                ...options,
                ...params,
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getApiFacebookMessagesByChatIdInfiniteQueryKey(options)
    });
};
