service:
  logLevel: debug
  port: 8080

mongo:
  connectionString: mongodb://root:root@localhost:27017
  databaseName: dataviewer
  facebookImportsCollection: facebook_imports
  facebookAccountsCollection: facebook_accounts
  facebookChatsCollection: facebook_chats
  facebookMessagesCollection: facebook_messages
