// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/wsngamerz/dataviewer/internal/domain"
	"github.com/wsngamerz/dataviewer/internal/dtos"
)

// NewMockFacebookUseCase creates a new instance of MockFacebookUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFacebookUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFacebookUseCase {
	mock := &MockFacebookUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFacebookUseCase is an autogenerated mock type for the FacebookUseCase type
type MockFacebookUseCase struct {
	mock.Mock
}

type MockFacebookUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFacebookUseCase) EXPECT() *MockFacebookUseCase_Expecter {
	return &MockFacebookUseCase_Expecter{mock: &_m.Mock}
}

// CreateImport provides a mock function for the type MockFacebookUseCase
func (_mock *MockFacebookUseCase) CreateImport(ctx context.Context, createImportRequest domain.CreateFacebookImport) (dtos.ImportDTO, error) {
	ret := _mock.Called(ctx, createImportRequest)

	if len(ret) == 0 {
		panic("no return value specified for CreateImport")
	}

	var r0 dtos.ImportDTO
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.CreateFacebookImport) (dtos.ImportDTO, error)); ok {
		return returnFunc(ctx, createImportRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.CreateFacebookImport) dtos.ImportDTO); ok {
		r0 = returnFunc(ctx, createImportRequest)
	} else {
		r0 = ret.Get(0).(dtos.ImportDTO)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.CreateFacebookImport) error); ok {
		r1 = returnFunc(ctx, createImportRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFacebookUseCase_CreateImport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateImport'
type MockFacebookUseCase_CreateImport_Call struct {
	*mock.Call
}

// CreateImport is a helper method to define mock.On call
//   - ctx context.Context
//   - createImportRequest domain.CreateFacebookImport
func (_e *MockFacebookUseCase_Expecter) CreateImport(ctx interface{}, createImportRequest interface{}) *MockFacebookUseCase_CreateImport_Call {
	return &MockFacebookUseCase_CreateImport_Call{Call: _e.mock.On("CreateImport", ctx, createImportRequest)}
}

func (_c *MockFacebookUseCase_CreateImport_Call) Run(run func(ctx context.Context, createImportRequest domain.CreateFacebookImport)) *MockFacebookUseCase_CreateImport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.CreateFacebookImport
		if args[1] != nil {
			arg1 = args[1].(domain.CreateFacebookImport)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFacebookUseCase_CreateImport_Call) Return(importDTO dtos.ImportDTO, err error) *MockFacebookUseCase_CreateImport_Call {
	_c.Call.Return(importDTO, err)
	return _c
}

func (_c *MockFacebookUseCase_CreateImport_Call) RunAndReturn(run func(ctx context.Context, createImportRequest domain.CreateFacebookImport) (dtos.ImportDTO, error)) *MockFacebookUseCase_CreateImport_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccounts provides a mock function for the type MockFacebookUseCase
func (_mock *MockFacebookUseCase) GetAccounts(ctx context.Context) ([]dtos.AccountDTO, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAccounts")
	}

	var r0 []dtos.AccountDTO
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]dtos.AccountDTO, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []dtos.AccountDTO); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dtos.AccountDTO)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFacebookUseCase_GetAccounts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccounts'
type MockFacebookUseCase_GetAccounts_Call struct {
	*mock.Call
}

// GetAccounts is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockFacebookUseCase_Expecter) GetAccounts(ctx interface{}) *MockFacebookUseCase_GetAccounts_Call {
	return &MockFacebookUseCase_GetAccounts_Call{Call: _e.mock.On("GetAccounts", ctx)}
}

func (_c *MockFacebookUseCase_GetAccounts_Call) Run(run func(ctx context.Context)) *MockFacebookUseCase_GetAccounts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFacebookUseCase_GetAccounts_Call) Return(accountDTOs []dtos.AccountDTO, err error) *MockFacebookUseCase_GetAccounts_Call {
	_c.Call.Return(accountDTOs, err)
	return _c
}

func (_c *MockFacebookUseCase_GetAccounts_Call) RunAndReturn(run func(ctx context.Context) ([]dtos.AccountDTO, error)) *MockFacebookUseCase_GetAccounts_Call {
	_c.Call.Return(run)
	return _c
}

// GetChatByID provides a mock function for the type MockFacebookUseCase
func (_mock *MockFacebookUseCase) GetChatByID(ctx context.Context, id string) (dtos.ChatDTO, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetChatByID")
	}

	var r0 dtos.ChatDTO
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (dtos.ChatDTO, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) dtos.ChatDTO); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(dtos.ChatDTO)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFacebookUseCase_GetChatByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChatByID'
type MockFacebookUseCase_GetChatByID_Call struct {
	*mock.Call
}

// GetChatByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockFacebookUseCase_Expecter) GetChatByID(ctx interface{}, id interface{}) *MockFacebookUseCase_GetChatByID_Call {
	return &MockFacebookUseCase_GetChatByID_Call{Call: _e.mock.On("GetChatByID", ctx, id)}
}

func (_c *MockFacebookUseCase_GetChatByID_Call) Run(run func(ctx context.Context, id string)) *MockFacebookUseCase_GetChatByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFacebookUseCase_GetChatByID_Call) Return(chatDTO dtos.ChatDTO, err error) *MockFacebookUseCase_GetChatByID_Call {
	_c.Call.Return(chatDTO, err)
	return _c
}

func (_c *MockFacebookUseCase_GetChatByID_Call) RunAndReturn(run func(ctx context.Context, id string) (dtos.ChatDTO, error)) *MockFacebookUseCase_GetChatByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetChats provides a mock function for the type MockFacebookUseCase
func (_mock *MockFacebookUseCase) GetChats(ctx context.Context) ([]dtos.ChatDTO, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetChats")
	}

	var r0 []dtos.ChatDTO
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]dtos.ChatDTO, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []dtos.ChatDTO); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dtos.ChatDTO)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFacebookUseCase_GetChats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChats'
type MockFacebookUseCase_GetChats_Call struct {
	*mock.Call
}

// GetChats is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockFacebookUseCase_Expecter) GetChats(ctx interface{}) *MockFacebookUseCase_GetChats_Call {
	return &MockFacebookUseCase_GetChats_Call{Call: _e.mock.On("GetChats", ctx)}
}

func (_c *MockFacebookUseCase_GetChats_Call) Run(run func(ctx context.Context)) *MockFacebookUseCase_GetChats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFacebookUseCase_GetChats_Call) Return(chatDTOs []dtos.ChatDTO, err error) *MockFacebookUseCase_GetChats_Call {
	_c.Call.Return(chatDTOs, err)
	return _c
}

func (_c *MockFacebookUseCase_GetChats_Call) RunAndReturn(run func(ctx context.Context) ([]dtos.ChatDTO, error)) *MockFacebookUseCase_GetChats_Call {
	_c.Call.Return(run)
	return _c
}

// GetImports provides a mock function for the type MockFacebookUseCase
func (_mock *MockFacebookUseCase) GetImports(ctx context.Context) ([]dtos.ImportDTO, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetImports")
	}

	var r0 []dtos.ImportDTO
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]dtos.ImportDTO, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []dtos.ImportDTO); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dtos.ImportDTO)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFacebookUseCase_GetImports_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetImports'
type MockFacebookUseCase_GetImports_Call struct {
	*mock.Call
}

// GetImports is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockFacebookUseCase_Expecter) GetImports(ctx interface{}) *MockFacebookUseCase_GetImports_Call {
	return &MockFacebookUseCase_GetImports_Call{Call: _e.mock.On("GetImports", ctx)}
}

func (_c *MockFacebookUseCase_GetImports_Call) Run(run func(ctx context.Context)) *MockFacebookUseCase_GetImports_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFacebookUseCase_GetImports_Call) Return(importDTOs []dtos.ImportDTO, err error) *MockFacebookUseCase_GetImports_Call {
	_c.Call.Return(importDTOs, err)
	return _c
}

func (_c *MockFacebookUseCase_GetImports_Call) RunAndReturn(run func(ctx context.Context) ([]dtos.ImportDTO, error)) *MockFacebookUseCase_GetImports_Call {
	_c.Call.Return(run)
	return _c
}

// GetMessages provides a mock function for the type MockFacebookUseCase
func (_mock *MockFacebookUseCase) GetMessages(ctx context.Context) ([]dtos.MessageDTO, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetMessages")
	}

	var r0 []dtos.MessageDTO
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]dtos.MessageDTO, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []dtos.MessageDTO); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dtos.MessageDTO)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFacebookUseCase_GetMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMessages'
type MockFacebookUseCase_GetMessages_Call struct {
	*mock.Call
}

// GetMessages is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockFacebookUseCase_Expecter) GetMessages(ctx interface{}) *MockFacebookUseCase_GetMessages_Call {
	return &MockFacebookUseCase_GetMessages_Call{Call: _e.mock.On("GetMessages", ctx)}
}

func (_c *MockFacebookUseCase_GetMessages_Call) Run(run func(ctx context.Context)) *MockFacebookUseCase_GetMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFacebookUseCase_GetMessages_Call) Return(messageDTOs []dtos.MessageDTO, err error) *MockFacebookUseCase_GetMessages_Call {
	_c.Call.Return(messageDTOs, err)
	return _c
}

func (_c *MockFacebookUseCase_GetMessages_Call) RunAndReturn(run func(ctx context.Context) ([]dtos.MessageDTO, error)) *MockFacebookUseCase_GetMessages_Call {
	_c.Call.Return(run)
	return _c
}

// GetMessagesByChatID provides a mock function for the type MockFacebookUseCase
func (_mock *MockFacebookUseCase) GetMessagesByChatID(ctx context.Context, chatID string, limit int, offset int) ([]dtos.MessageDTO, int, error) {
	ret := _mock.Called(ctx, chatID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetMessagesByChatID")
	}

	var r0 []dtos.MessageDTO
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, int) ([]dtos.MessageDTO, int, error)); ok {
		return returnFunc(ctx, chatID, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, int) []dtos.MessageDTO); ok {
		r0 = returnFunc(ctx, chatID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dtos.MessageDTO)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int, int) int); ok {
		r1 = returnFunc(ctx, chatID, limit, offset)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, int, int) error); ok {
		r2 = returnFunc(ctx, chatID, limit, offset)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockFacebookUseCase_GetMessagesByChatID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMessagesByChatID'
type MockFacebookUseCase_GetMessagesByChatID_Call struct {
	*mock.Call
}

// GetMessagesByChatID is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID string
//   - limit int
//   - offset int
func (_e *MockFacebookUseCase_Expecter) GetMessagesByChatID(ctx interface{}, chatID interface{}, limit interface{}, offset interface{}) *MockFacebookUseCase_GetMessagesByChatID_Call {
	return &MockFacebookUseCase_GetMessagesByChatID_Call{Call: _e.mock.On("GetMessagesByChatID", ctx, chatID, limit, offset)}
}

func (_c *MockFacebookUseCase_GetMessagesByChatID_Call) Run(run func(ctx context.Context, chatID string, limit int, offset int)) *MockFacebookUseCase_GetMessagesByChatID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockFacebookUseCase_GetMessagesByChatID_Call) Return(messageDTOs []dtos.MessageDTO, n int, err error) *MockFacebookUseCase_GetMessagesByChatID_Call {
	_c.Call.Return(messageDTOs, n, err)
	return _c
}

func (_c *MockFacebookUseCase_GetMessagesByChatID_Call) RunAndReturn(run func(ctx context.Context, chatID string, limit int, offset int) ([]dtos.MessageDTO, int, error)) *MockFacebookUseCase_GetMessagesByChatID_Call {
	_c.Call.Return(run)
	return _c
}
