// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/wsngamerz/dataviewer/internal/domain"
	"github.com/wsngamerz/dataviewer/internal/dtos"
)

// NewMockFacebookUseCase creates a new instance of MockFacebookUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFacebookUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFacebookUseCase {
	mock := &MockFacebookUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFacebookUseCase is an autogenerated mock type for the FacebookUseCase type
type MockFacebookUseCase struct {
	mock.Mock
}

type MockFacebookUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFacebookUseCase) EXPECT() *MockFacebookUseCase_Expecter {
	return &MockFacebookUseCase_Expecter{mock: &_m.Mock}
}

// CreateImport provides a mock function for the type MockFacebookUseCase
func (_mock *MockFacebookUseCase) CreateImport(ctx context.Context, createImportRequest domain.CreateFacebookImport) (dtos.ImportDTO, error) {
	ret := _mock.Called(ctx, createImportRequest)

	if len(ret) == 0 {
		panic("no return value specified for CreateImport")
	}

	var r0 dtos.ImportDTO
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.CreateFacebookImport) (dtos.ImportDTO, error)); ok {
		return returnFunc(ctx, createImportRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.CreateFacebookImport) dtos.ImportDTO); ok {
		r0 = returnFunc(ctx, createImportRequest)
	} else {
		r0 = ret.Get(0).(dtos.ImportDTO)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.CreateFacebookImport) error); ok {
		r1 = returnFunc(ctx, createImportRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFacebookUseCase_CreateImport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateImport'
type MockFacebookUseCase_CreateImport_Call struct {
	*mock.Call
}

// CreateImport is a helper method to define mock.On call
//   - ctx context.Context
//   - createImportRequest domain.CreateFacebookImport
func (_e *MockFacebookUseCase_Expecter) CreateImport(ctx interface{}, createImportRequest interface{}) *MockFacebookUseCase_CreateImport_Call {
	return &MockFacebookUseCase_CreateImport_Call{Call: _e.mock.On("CreateImport", ctx, createImportRequest)}
}

func (_c *MockFacebookUseCase_CreateImport_Call) Run(run func(ctx context.Context, createImportRequest domain.CreateFacebookImport)) *MockFacebookUseCase_CreateImport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.CreateFacebookImport
		if args[1] != nil {
			arg1 = args[1].(domain.CreateFacebookImport)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFacebookUseCase_CreateImport_Call) Return(importDTO dtos.ImportDTO, err error) *MockFacebookUseCase_CreateImport_Call {
	_c.Call.Return(importDTO, err)
	return _c
}

func (_c *MockFacebookUseCase_CreateImport_Call) RunAndReturn(run func(ctx context.Context, createImportRequest domain.CreateFacebookImport) (dtos.ImportDTO, error)) *MockFacebookUseCase_CreateImport_Call {
	_c.Call.Return(run)
	return _c
}

// GetImports provides a mock function for the type MockFacebookUseCase
func (_mock *MockFacebookUseCase) GetImports(ctx context.Context) ([]dtos.ImportDTO, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetImports")
	}

	var r0 []dtos.ImportDTO
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]dtos.ImportDTO, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []dtos.ImportDTO); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dtos.ImportDTO)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFacebookUseCase_GetImports_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetImports'
type MockFacebookUseCase_GetImports_Call struct {
	*mock.Call
}

// GetImports is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockFacebookUseCase_Expecter) GetImports(ctx interface{}) *MockFacebookUseCase_GetImports_Call {
	return &MockFacebookUseCase_GetImports_Call{Call: _e.mock.On("GetImports", ctx)}
}

func (_c *MockFacebookUseCase_GetImports_Call) Run(run func(ctx context.Context)) *MockFacebookUseCase_GetImports_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFacebookUseCase_GetImports_Call) Return(importDTOs []dtos.ImportDTO, err error) *MockFacebookUseCase_GetImports_Call {
	_c.Call.Return(importDTOs, err)
	return _c
}

func (_c *MockFacebookUseCase_GetImports_Call) RunAndReturn(run func(ctx context.Context) ([]dtos.ImportDTO, error)) *MockFacebookUseCase_GetImports_Call {
	_c.Call.Return(run)
	return _c
}
