// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/wsngamerz/dataviewer/internal/models"
)

// NewMockFacebookRepo creates a new instance of MockFacebookRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFacebookRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFacebookRepo {
	mock := &MockFacebookRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFacebookRepo is an autogenerated mock type for the FacebookRepo type
type MockFacebookRepo struct {
	mock.Mock
}

type MockFacebookRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFacebookRepo) EXPECT() *MockFacebookRepo_Expecter {
	return &MockFacebookRepo_Expecter{mock: &_m.Mock}
}

// CreateImport provides a mock function for the type MockFacebookRepo
func (_mock *MockFacebookRepo) CreateImport(ctx context.Context, i models.Import) error {
	ret := _mock.Called(ctx, i)

	if len(ret) == 0 {
		panic("no return value specified for CreateImport")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Import) error); ok {
		r0 = returnFunc(ctx, i)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFacebookRepo_CreateImport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateImport'
type MockFacebookRepo_CreateImport_Call struct {
	*mock.Call
}

// CreateImport is a helper method to define mock.On call
//   - ctx context.Context
//   - i models.Import
func (_e *MockFacebookRepo_Expecter) CreateImport(ctx interface{}, i interface{}) *MockFacebookRepo_CreateImport_Call {
	return &MockFacebookRepo_CreateImport_Call{Call: _e.mock.On("CreateImport", ctx, i)}
}

func (_c *MockFacebookRepo_CreateImport_Call) Run(run func(ctx context.Context, i models.Import)) *MockFacebookRepo_CreateImport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Import
		if args[1] != nil {
			arg1 = args[1].(models.Import)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFacebookRepo_CreateImport_Call) Return(err error) *MockFacebookRepo_CreateImport_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFacebookRepo_CreateImport_Call) RunAndReturn(run func(ctx context.Context, i models.Import) error) *MockFacebookRepo_CreateImport_Call {
	_c.Call.Return(run)
	return _c
}

// GetImport provides a mock function for the type MockFacebookRepo
func (_mock *MockFacebookRepo) GetImport(ctx context.Context, id string) (*models.Import, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetImport")
	}

	var r0 *models.Import
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.Import, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.Import); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Import)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFacebookRepo_GetImport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetImport'
type MockFacebookRepo_GetImport_Call struct {
	*mock.Call
}

// GetImport is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockFacebookRepo_Expecter) GetImport(ctx interface{}, id interface{}) *MockFacebookRepo_GetImport_Call {
	return &MockFacebookRepo_GetImport_Call{Call: _e.mock.On("GetImport", ctx, id)}
}

func (_c *MockFacebookRepo_GetImport_Call) Run(run func(ctx context.Context, id string)) *MockFacebookRepo_GetImport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFacebookRepo_GetImport_Call) Return(importParam *models.Import, err error) *MockFacebookRepo_GetImport_Call {
	_c.Call.Return(importParam, err)
	return _c
}

func (_c *MockFacebookRepo_GetImport_Call) RunAndReturn(run func(ctx context.Context, id string) (*models.Import, error)) *MockFacebookRepo_GetImport_Call {
	_c.Call.Return(run)
	return _c
}

// GetImports provides a mock function for the type MockFacebookRepo
func (_mock *MockFacebookRepo) GetImports(ctx context.Context) ([]models.Import, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetImports")
	}

	var r0 []models.Import
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]models.Import, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []models.Import); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Import)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFacebookRepo_GetImports_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetImports'
type MockFacebookRepo_GetImports_Call struct {
	*mock.Call
}

// GetImports is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockFacebookRepo_Expecter) GetImports(ctx interface{}) *MockFacebookRepo_GetImports_Call {
	return &MockFacebookRepo_GetImports_Call{Call: _e.mock.On("GetImports", ctx)}
}

func (_c *MockFacebookRepo_GetImports_Call) Run(run func(ctx context.Context)) *MockFacebookRepo_GetImports_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFacebookRepo_GetImports_Call) Return(imports []models.Import, err error) *MockFacebookRepo_GetImports_Call {
	_c.Call.Return(imports, err)
	return _c
}

func (_c *MockFacebookRepo_GetImports_Call) RunAndReturn(run func(ctx context.Context) ([]models.Import, error)) *MockFacebookRepo_GetImports_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateImport provides a mock function for the type MockFacebookRepo
func (_mock *MockFacebookRepo) UpdateImport(ctx context.Context, i models.Import) error {
	ret := _mock.Called(ctx, i)

	if len(ret) == 0 {
		panic("no return value specified for UpdateImport")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Import) error); ok {
		r0 = returnFunc(ctx, i)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFacebookRepo_UpdateImport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateImport'
type MockFacebookRepo_UpdateImport_Call struct {
	*mock.Call
}

// UpdateImport is a helper method to define mock.On call
//   - ctx context.Context
//   - i models.Import
func (_e *MockFacebookRepo_Expecter) UpdateImport(ctx interface{}, i interface{}) *MockFacebookRepo_UpdateImport_Call {
	return &MockFacebookRepo_UpdateImport_Call{Call: _e.mock.On("UpdateImport", ctx, i)}
}

func (_c *MockFacebookRepo_UpdateImport_Call) Run(run func(ctx context.Context, i models.Import)) *MockFacebookRepo_UpdateImport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Import
		if args[1] != nil {
			arg1 = args[1].(models.Import)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFacebookRepo_UpdateImport_Call) Return(err error) *MockFacebookRepo_UpdateImport_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFacebookRepo_UpdateImport_Call) RunAndReturn(run func(ctx context.Context, i models.Import) error) *MockFacebookRepo_UpdateImport_Call {
	_c.Call.Return(run)
	return _c
}
