// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/wsngamerz/dataviewer/internal/models"
)

// NewMockFacebookRepo creates a new instance of MockFacebookRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFacebookRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFacebookRepo {
	mock := &MockFacebookRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFacebookRepo is an autogenerated mock type for the FacebookRepo type
type MockFacebookRepo struct {
	mock.Mock
}

type MockFacebookRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFacebookRepo) EXPECT() *MockFacebookRepo_Expecter {
	return &MockFacebookRepo_Expecter{mock: &_m.Mock}
}

// CreateAccount provides a mock function for the type MockFacebookRepo
func (_mock *MockFacebookRepo) CreateAccount(ctx context.Context, a models.Account) error {
	ret := _mock.Called(ctx, a)

	if len(ret) == 0 {
		panic("no return value specified for CreateAccount")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Account) error); ok {
		r0 = returnFunc(ctx, a)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFacebookRepo_CreateAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAccount'
type MockFacebookRepo_CreateAccount_Call struct {
	*mock.Call
}

// CreateAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - a models.Account
func (_e *MockFacebookRepo_Expecter) CreateAccount(ctx interface{}, a interface{}) *MockFacebookRepo_CreateAccount_Call {
	return &MockFacebookRepo_CreateAccount_Call{Call: _e.mock.On("CreateAccount", ctx, a)}
}

func (_c *MockFacebookRepo_CreateAccount_Call) Run(run func(ctx context.Context, a models.Account)) *MockFacebookRepo_CreateAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Account
		if args[1] != nil {
			arg1 = args[1].(models.Account)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFacebookRepo_CreateAccount_Call) Return(err error) *MockFacebookRepo_CreateAccount_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFacebookRepo_CreateAccount_Call) RunAndReturn(run func(ctx context.Context, a models.Account) error) *MockFacebookRepo_CreateAccount_Call {
	_c.Call.Return(run)
	return _c
}

// CreateChat provides a mock function for the type MockFacebookRepo
func (_mock *MockFacebookRepo) CreateChat(ctx context.Context, c models.Chat) error {
	ret := _mock.Called(ctx, c)

	if len(ret) == 0 {
		panic("no return value specified for CreateChat")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Chat) error); ok {
		r0 = returnFunc(ctx, c)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFacebookRepo_CreateChat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateChat'
type MockFacebookRepo_CreateChat_Call struct {
	*mock.Call
}

// CreateChat is a helper method to define mock.On call
//   - ctx context.Context
//   - c models.Chat
func (_e *MockFacebookRepo_Expecter) CreateChat(ctx interface{}, c interface{}) *MockFacebookRepo_CreateChat_Call {
	return &MockFacebookRepo_CreateChat_Call{Call: _e.mock.On("CreateChat", ctx, c)}
}

func (_c *MockFacebookRepo_CreateChat_Call) Run(run func(ctx context.Context, c models.Chat)) *MockFacebookRepo_CreateChat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Chat
		if args[1] != nil {
			arg1 = args[1].(models.Chat)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFacebookRepo_CreateChat_Call) Return(err error) *MockFacebookRepo_CreateChat_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFacebookRepo_CreateChat_Call) RunAndReturn(run func(ctx context.Context, c models.Chat) error) *MockFacebookRepo_CreateChat_Call {
	_c.Call.Return(run)
	return _c
}

// CreateImport provides a mock function for the type MockFacebookRepo
func (_mock *MockFacebookRepo) CreateImport(ctx context.Context, i models.Import) error {
	ret := _mock.Called(ctx, i)

	if len(ret) == 0 {
		panic("no return value specified for CreateImport")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Import) error); ok {
		r0 = returnFunc(ctx, i)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFacebookRepo_CreateImport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateImport'
type MockFacebookRepo_CreateImport_Call struct {
	*mock.Call
}

// CreateImport is a helper method to define mock.On call
//   - ctx context.Context
//   - i models.Import
func (_e *MockFacebookRepo_Expecter) CreateImport(ctx interface{}, i interface{}) *MockFacebookRepo_CreateImport_Call {
	return &MockFacebookRepo_CreateImport_Call{Call: _e.mock.On("CreateImport", ctx, i)}
}

func (_c *MockFacebookRepo_CreateImport_Call) Run(run func(ctx context.Context, i models.Import)) *MockFacebookRepo_CreateImport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Import
		if args[1] != nil {
			arg1 = args[1].(models.Import)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFacebookRepo_CreateImport_Call) Return(err error) *MockFacebookRepo_CreateImport_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFacebookRepo_CreateImport_Call) RunAndReturn(run func(ctx context.Context, i models.Import) error) *MockFacebookRepo_CreateImport_Call {
	_c.Call.Return(run)
	return _c
}

// CreateMessage provides a mock function for the type MockFacebookRepo
func (_mock *MockFacebookRepo) CreateMessage(ctx context.Context, m models.Message) error {
	ret := _mock.Called(ctx, m)

	if len(ret) == 0 {
		panic("no return value specified for CreateMessage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Message) error); ok {
		r0 = returnFunc(ctx, m)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFacebookRepo_CreateMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMessage'
type MockFacebookRepo_CreateMessage_Call struct {
	*mock.Call
}

// CreateMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - m models.Message
func (_e *MockFacebookRepo_Expecter) CreateMessage(ctx interface{}, m interface{}) *MockFacebookRepo_CreateMessage_Call {
	return &MockFacebookRepo_CreateMessage_Call{Call: _e.mock.On("CreateMessage", ctx, m)}
}

func (_c *MockFacebookRepo_CreateMessage_Call) Run(run func(ctx context.Context, m models.Message)) *MockFacebookRepo_CreateMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Message
		if args[1] != nil {
			arg1 = args[1].(models.Message)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFacebookRepo_CreateMessage_Call) Return(err error) *MockFacebookRepo_CreateMessage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFacebookRepo_CreateMessage_Call) RunAndReturn(run func(ctx context.Context, m models.Message) error) *MockFacebookRepo_CreateMessage_Call {
	_c.Call.Return(run)
	return _c
}

// CreateMessagesBulk provides a mock function for the type MockFacebookRepo
func (_mock *MockFacebookRepo) CreateMessagesBulk(ctx context.Context, messages []models.Message) error {
	ret := _mock.Called(ctx, messages)

	if len(ret) == 0 {
		panic("no return value specified for CreateMessagesBulk")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []models.Message) error); ok {
		r0 = returnFunc(ctx, messages)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFacebookRepo_CreateMessagesBulk_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMessagesBulk'
type MockFacebookRepo_CreateMessagesBulk_Call struct {
	*mock.Call
}

// CreateMessagesBulk is a helper method to define mock.On call
//   - ctx context.Context
//   - messages []models.Message
func (_e *MockFacebookRepo_Expecter) CreateMessagesBulk(ctx interface{}, messages interface{}) *MockFacebookRepo_CreateMessagesBulk_Call {
	return &MockFacebookRepo_CreateMessagesBulk_Call{Call: _e.mock.On("CreateMessagesBulk", ctx, messages)}
}

func (_c *MockFacebookRepo_CreateMessagesBulk_Call) Run(run func(ctx context.Context, messages []models.Message)) *MockFacebookRepo_CreateMessagesBulk_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []models.Message
		if args[1] != nil {
			arg1 = args[1].([]models.Message)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFacebookRepo_CreateMessagesBulk_Call) Return(err error) *MockFacebookRepo_CreateMessagesBulk_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFacebookRepo_CreateMessagesBulk_Call) RunAndReturn(run func(ctx context.Context, messages []models.Message) error) *MockFacebookRepo_CreateMessagesBulk_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccounts provides a mock function for the type MockFacebookRepo
func (_mock *MockFacebookRepo) GetAccounts(ctx context.Context) ([]models.Account, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAccounts")
	}

	var r0 []models.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]models.Account, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []models.Account); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFacebookRepo_GetAccounts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccounts'
type MockFacebookRepo_GetAccounts_Call struct {
	*mock.Call
}

// GetAccounts is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockFacebookRepo_Expecter) GetAccounts(ctx interface{}) *MockFacebookRepo_GetAccounts_Call {
	return &MockFacebookRepo_GetAccounts_Call{Call: _e.mock.On("GetAccounts", ctx)}
}

func (_c *MockFacebookRepo_GetAccounts_Call) Run(run func(ctx context.Context)) *MockFacebookRepo_GetAccounts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFacebookRepo_GetAccounts_Call) Return(accounts []models.Account, err error) *MockFacebookRepo_GetAccounts_Call {
	_c.Call.Return(accounts, err)
	return _c
}

func (_c *MockFacebookRepo_GetAccounts_Call) RunAndReturn(run func(ctx context.Context) ([]models.Account, error)) *MockFacebookRepo_GetAccounts_Call {
	_c.Call.Return(run)
	return _c
}

// GetChatByID provides a mock function for the type MockFacebookRepo
func (_mock *MockFacebookRepo) GetChatByID(ctx context.Context, id string) (*models.Chat, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetChatByID")
	}

	var r0 *models.Chat
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.Chat, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.Chat); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Chat)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFacebookRepo_GetChatByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChatByID'
type MockFacebookRepo_GetChatByID_Call struct {
	*mock.Call
}

// GetChatByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockFacebookRepo_Expecter) GetChatByID(ctx interface{}, id interface{}) *MockFacebookRepo_GetChatByID_Call {
	return &MockFacebookRepo_GetChatByID_Call{Call: _e.mock.On("GetChatByID", ctx, id)}
}

func (_c *MockFacebookRepo_GetChatByID_Call) Run(run func(ctx context.Context, id string)) *MockFacebookRepo_GetChatByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFacebookRepo_GetChatByID_Call) Return(chat *models.Chat, err error) *MockFacebookRepo_GetChatByID_Call {
	_c.Call.Return(chat, err)
	return _c
}

func (_c *MockFacebookRepo_GetChatByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*models.Chat, error)) *MockFacebookRepo_GetChatByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetChatByThreadPath provides a mock function for the type MockFacebookRepo
func (_mock *MockFacebookRepo) GetChatByThreadPath(ctx context.Context, threadPath string) (*models.Chat, error) {
	ret := _mock.Called(ctx, threadPath)

	if len(ret) == 0 {
		panic("no return value specified for GetChatByThreadPath")
	}

	var r0 *models.Chat
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.Chat, error)); ok {
		return returnFunc(ctx, threadPath)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.Chat); ok {
		r0 = returnFunc(ctx, threadPath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Chat)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, threadPath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFacebookRepo_GetChatByThreadPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChatByThreadPath'
type MockFacebookRepo_GetChatByThreadPath_Call struct {
	*mock.Call
}

// GetChatByThreadPath is a helper method to define mock.On call
//   - ctx context.Context
//   - threadPath string
func (_e *MockFacebookRepo_Expecter) GetChatByThreadPath(ctx interface{}, threadPath interface{}) *MockFacebookRepo_GetChatByThreadPath_Call {
	return &MockFacebookRepo_GetChatByThreadPath_Call{Call: _e.mock.On("GetChatByThreadPath", ctx, threadPath)}
}

func (_c *MockFacebookRepo_GetChatByThreadPath_Call) Run(run func(ctx context.Context, threadPath string)) *MockFacebookRepo_GetChatByThreadPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFacebookRepo_GetChatByThreadPath_Call) Return(chat *models.Chat, err error) *MockFacebookRepo_GetChatByThreadPath_Call {
	_c.Call.Return(chat, err)
	return _c
}

func (_c *MockFacebookRepo_GetChatByThreadPath_Call) RunAndReturn(run func(ctx context.Context, threadPath string) (*models.Chat, error)) *MockFacebookRepo_GetChatByThreadPath_Call {
	_c.Call.Return(run)
	return _c
}

// GetChats provides a mock function for the type MockFacebookRepo
func (_mock *MockFacebookRepo) GetChats(ctx context.Context) ([]models.Chat, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetChats")
	}

	var r0 []models.Chat
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]models.Chat, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []models.Chat); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Chat)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFacebookRepo_GetChats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChats'
type MockFacebookRepo_GetChats_Call struct {
	*mock.Call
}

// GetChats is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockFacebookRepo_Expecter) GetChats(ctx interface{}) *MockFacebookRepo_GetChats_Call {
	return &MockFacebookRepo_GetChats_Call{Call: _e.mock.On("GetChats", ctx)}
}

func (_c *MockFacebookRepo_GetChats_Call) Run(run func(ctx context.Context)) *MockFacebookRepo_GetChats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFacebookRepo_GetChats_Call) Return(chats []models.Chat, err error) *MockFacebookRepo_GetChats_Call {
	_c.Call.Return(chats, err)
	return _c
}

func (_c *MockFacebookRepo_GetChats_Call) RunAndReturn(run func(ctx context.Context) ([]models.Chat, error)) *MockFacebookRepo_GetChats_Call {
	_c.Call.Return(run)
	return _c
}

// GetImport provides a mock function for the type MockFacebookRepo
func (_mock *MockFacebookRepo) GetImport(ctx context.Context, id string) (*models.Import, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetImport")
	}

	var r0 *models.Import
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.Import, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.Import); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Import)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFacebookRepo_GetImport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetImport'
type MockFacebookRepo_GetImport_Call struct {
	*mock.Call
}

// GetImport is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockFacebookRepo_Expecter) GetImport(ctx interface{}, id interface{}) *MockFacebookRepo_GetImport_Call {
	return &MockFacebookRepo_GetImport_Call{Call: _e.mock.On("GetImport", ctx, id)}
}

func (_c *MockFacebookRepo_GetImport_Call) Run(run func(ctx context.Context, id string)) *MockFacebookRepo_GetImport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFacebookRepo_GetImport_Call) Return(importParam *models.Import, err error) *MockFacebookRepo_GetImport_Call {
	_c.Call.Return(importParam, err)
	return _c
}

func (_c *MockFacebookRepo_GetImport_Call) RunAndReturn(run func(ctx context.Context, id string) (*models.Import, error)) *MockFacebookRepo_GetImport_Call {
	_c.Call.Return(run)
	return _c
}

// GetImports provides a mock function for the type MockFacebookRepo
func (_mock *MockFacebookRepo) GetImports(ctx context.Context) ([]models.Import, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetImports")
	}

	var r0 []models.Import
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]models.Import, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []models.Import); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Import)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFacebookRepo_GetImports_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetImports'
type MockFacebookRepo_GetImports_Call struct {
	*mock.Call
}

// GetImports is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockFacebookRepo_Expecter) GetImports(ctx interface{}) *MockFacebookRepo_GetImports_Call {
	return &MockFacebookRepo_GetImports_Call{Call: _e.mock.On("GetImports", ctx)}
}

func (_c *MockFacebookRepo_GetImports_Call) Run(run func(ctx context.Context)) *MockFacebookRepo_GetImports_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFacebookRepo_GetImports_Call) Return(imports []models.Import, err error) *MockFacebookRepo_GetImports_Call {
	_c.Call.Return(imports, err)
	return _c
}

func (_c *MockFacebookRepo_GetImports_Call) RunAndReturn(run func(ctx context.Context) ([]models.Import, error)) *MockFacebookRepo_GetImports_Call {
	_c.Call.Return(run)
	return _c
}

// GetMessages provides a mock function for the type MockFacebookRepo
func (_mock *MockFacebookRepo) GetMessages(ctx context.Context) ([]models.Message, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetMessages")
	}

	var r0 []models.Message
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]models.Message, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []models.Message); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Message)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFacebookRepo_GetMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMessages'
type MockFacebookRepo_GetMessages_Call struct {
	*mock.Call
}

// GetMessages is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockFacebookRepo_Expecter) GetMessages(ctx interface{}) *MockFacebookRepo_GetMessages_Call {
	return &MockFacebookRepo_GetMessages_Call{Call: _e.mock.On("GetMessages", ctx)}
}

func (_c *MockFacebookRepo_GetMessages_Call) Run(run func(ctx context.Context)) *MockFacebookRepo_GetMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFacebookRepo_GetMessages_Call) Return(messages []models.Message, err error) *MockFacebookRepo_GetMessages_Call {
	_c.Call.Return(messages, err)
	return _c
}

func (_c *MockFacebookRepo_GetMessages_Call) RunAndReturn(run func(ctx context.Context) ([]models.Message, error)) *MockFacebookRepo_GetMessages_Call {
	_c.Call.Return(run)
	return _c
}

// GetMessagesByChatID provides a mock function for the type MockFacebookRepo
func (_mock *MockFacebookRepo) GetMessagesByChatID(ctx context.Context, chatID string, page int, pageSize int) ([]models.Message, int, error) {
	ret := _mock.Called(ctx, chatID, page, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for GetMessagesByChatID")
	}

	var r0 []models.Message
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, int) ([]models.Message, int, error)); ok {
		return returnFunc(ctx, chatID, page, pageSize)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, int) []models.Message); ok {
		r0 = returnFunc(ctx, chatID, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Message)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int, int) int); ok {
		r1 = returnFunc(ctx, chatID, page, pageSize)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, int, int) error); ok {
		r2 = returnFunc(ctx, chatID, page, pageSize)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockFacebookRepo_GetMessagesByChatID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMessagesByChatID'
type MockFacebookRepo_GetMessagesByChatID_Call struct {
	*mock.Call
}

// GetMessagesByChatID is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID string
//   - page int
//   - pageSize int
func (_e *MockFacebookRepo_Expecter) GetMessagesByChatID(ctx interface{}, chatID interface{}, page interface{}, pageSize interface{}) *MockFacebookRepo_GetMessagesByChatID_Call {
	return &MockFacebookRepo_GetMessagesByChatID_Call{Call: _e.mock.On("GetMessagesByChatID", ctx, chatID, page, pageSize)}
}

func (_c *MockFacebookRepo_GetMessagesByChatID_Call) Run(run func(ctx context.Context, chatID string, page int, pageSize int)) *MockFacebookRepo_GetMessagesByChatID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockFacebookRepo_GetMessagesByChatID_Call) Return(messages []models.Message, n int, err error) *MockFacebookRepo_GetMessagesByChatID_Call {
	_c.Call.Return(messages, n, err)
	return _c
}

func (_c *MockFacebookRepo_GetMessagesByChatID_Call) RunAndReturn(run func(ctx context.Context, chatID string, page int, pageSize int) ([]models.Message, int, error)) *MockFacebookRepo_GetMessagesByChatID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateImport provides a mock function for the type MockFacebookRepo
func (_mock *MockFacebookRepo) UpdateImport(ctx context.Context, i models.Import) error {
	ret := _mock.Called(ctx, i)

	if len(ret) == 0 {
		panic("no return value specified for UpdateImport")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Import) error); ok {
		r0 = returnFunc(ctx, i)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFacebookRepo_UpdateImport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateImport'
type MockFacebookRepo_UpdateImport_Call struct {
	*mock.Call
}

// UpdateImport is a helper method to define mock.On call
//   - ctx context.Context
//   - i models.Import
func (_e *MockFacebookRepo_Expecter) UpdateImport(ctx interface{}, i interface{}) *MockFacebookRepo_UpdateImport_Call {
	return &MockFacebookRepo_UpdateImport_Call{Call: _e.mock.On("UpdateImport", ctx, i)}
}

func (_c *MockFacebookRepo_UpdateImport_Call) Run(run func(ctx context.Context, i models.Import)) *MockFacebookRepo_UpdateImport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Import
		if args[1] != nil {
			arg1 = args[1].(models.Import)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFacebookRepo_UpdateImport_Call) Return(err error) *MockFacebookRepo_UpdateImport_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFacebookRepo_UpdateImport_Call) RunAndReturn(run func(ctx context.Context, i models.Import) error) *MockFacebookRepo_UpdateImport_Call {
	_c.Call.Return(run)
	return _c
}
