// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { GetApiFacebookAccountsData, GetApiFacebookAccountsErrors, GetApiFacebookAccountsResponses, GetApiFacebookChatsByIdData, GetApiFacebookChatsByIdErrors, GetApiFacebookChatsByIdMessagesData, GetApiFacebookChatsByIdMessagesErrors, GetApiFacebookChatsByIdMessagesResponses, GetApiFacebookChatsByIdResponses, GetApiFacebookChatsByIdSummaryData, GetApiFacebookChatsByIdSummaryErrors, GetApiFacebookChatsByIdSummaryResponses, GetApiFacebookChatsData, GetApiFacebookChatsErrors, GetApiFacebookChatsResponses, GetApiFacebookImportsData, GetApiFacebookImportsErrors, GetApiFacebookImportsResponses, GetApiFacebookMessagesData, GetApiFacebookMessagesErrors, GetApiFacebookMessagesResponses, PostApiFacebookImportsData, PostApiFacebookImportsErrors, PostApiFacebookImportsResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get API facebook accounts
 */
export const getApiFacebookAccounts = <ThrowOnError extends boolean = false>(options?: Options<GetApiFacebookAccountsData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetApiFacebookAccountsResponses, GetApiFacebookAccountsErrors, ThrowOnError>({
        url: '/api/facebook/accounts',
        ...options
    });
};

/**
 * Get API facebook chats
 */
export const getApiFacebookChats = <ThrowOnError extends boolean = false>(options?: Options<GetApiFacebookChatsData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetApiFacebookChatsResponses, GetApiFacebookChatsErrors, ThrowOnError>({
        url: '/api/facebook/chats',
        ...options
    });
};

/**
 * Get API facebook chats by ID
 */
export const getApiFacebookChatsById = <ThrowOnError extends boolean = false>(options: Options<GetApiFacebookChatsByIdData, ThrowOnError>) => {
    return (options.client ?? client).get<GetApiFacebookChatsByIdResponses, GetApiFacebookChatsByIdErrors, ThrowOnError>({
        url: '/api/facebook/chats/{id}',
        ...options
    });
};

/**
 * Get API facebook chats by ID messages
 */
export const getApiFacebookChatsByIdMessages = <ThrowOnError extends boolean = false>(options: Options<GetApiFacebookChatsByIdMessagesData, ThrowOnError>) => {
    return (options.client ?? client).get<GetApiFacebookChatsByIdMessagesResponses, GetApiFacebookChatsByIdMessagesErrors, ThrowOnError>({
        url: '/api/facebook/chats/{id}/messages',
        ...options
    });
};

/**
 * Get API facebook chats by ID summary
 */
export const getApiFacebookChatsByIdSummary = <ThrowOnError extends boolean = false>(options: Options<GetApiFacebookChatsByIdSummaryData, ThrowOnError>) => {
    return (options.client ?? client).get<GetApiFacebookChatsByIdSummaryResponses, GetApiFacebookChatsByIdSummaryErrors, ThrowOnError>({
        url: '/api/facebook/chats/{id}/summary',
        ...options
    });
};

/**
 * Get API facebook imports
 */
export const getApiFacebookImports = <ThrowOnError extends boolean = false>(options?: Options<GetApiFacebookImportsData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetApiFacebookImportsResponses, GetApiFacebookImportsErrors, ThrowOnError>({
        url: '/api/facebook/imports',
        ...options
    });
};

/**
 * Post API facebook imports
 */
export const postApiFacebookImports = <ThrowOnError extends boolean = false>(options?: Options<PostApiFacebookImportsData, ThrowOnError>) => {
    return (options?.client ?? client).post<PostApiFacebookImportsResponses, PostApiFacebookImportsErrors, ThrowOnError>({
        ...formDataBodySerializer,
        url: '/api/facebook/imports',
        ...options,
        headers: {
            'Content-Type': null,
            ...options?.headers
        }
    });
};

/**
 * Get API facebook messages
 */
export const getApiFacebookMessages = <ThrowOnError extends boolean = false>(options?: Options<GetApiFacebookMessagesData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetApiFacebookMessagesResponses, GetApiFacebookMessagesErrors, ThrowOnError>({
        url: '/api/facebook/messages',
        ...options
    });
};
