// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type AccountDto = {
    created_at: string;
    id: string;
    name: string;
    timestamp: string;
    user_id: string;
};

export type ChatDto = {
    created_at: string;
    id: string;
    participant_ids: Array<string> | null;
    thread_path: string;
    title: string;
};

export type ChatSummaryDto = {
    estimated_created_at: string;
    id: string;
    last_message: MessageDto;
    message_count: number;
    participant_ids: Array<string> | null;
    title: string;
};

export type CreateImportResponseBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    import: ImportDto;
};

export type ErrorDetail = {
    /**
     * Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
     */
    location?: string;
    /**
     * Error message text
     */
    message?: string;
    /**
     * The value at the given location
     */
    value?: unknown;
};

export type ErrorModel = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    detail?: string;
    /**
     * Optional list of individual error details
     */
    errors?: Array<ErrorDetail> | null;
    /**
     * A URI reference that identifies the specific occurrence of the problem.
     */
    instance?: string;
    /**
     * HTTP status code
     */
    status?: number;
    /**
     * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
     */
    title?: string;
    /**
     * A URI reference to human-readable documentation for the error.
     */
    type?: string;
};

export type GetAccountsResponseBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    accounts: Array<AccountDto> | null;
};

export type GetChatByIdResponseBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    chat: ChatDto;
};

export type GetChatSummariesResponseBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    summaries: Array<ChatSummaryDto> | null;
};

export type GetChatSummaryResponseBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    summary: ChatSummaryDto;
};

export type GetChatsResponseBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    chats: Array<ChatDto> | null;
};

export type GetImportsResponseBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    imports: Array<ImportDto> | null;
};

export type GetMessagesByChatIdResponseBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    messages: Array<MessageDto> | null;
    page: number;
    pageCount: number;
    pageSize: number;
    total: number;
};

export type GetMessagesResponseBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    messages: Array<MessageDto> | null;
};

export type ImportDto = {
    created_at: string;
    filename: string;
    id: string;
    status: string;
};

export type MessageDto = {
    chat_id: string;
    content: string;
    created_at: string;
    id: string;
    sender_id: string;
    sent_at: string;
};

export type CreateImportResponseBodyWritable = {
    import: ImportDto;
};

export type ErrorModelWritable = {
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    detail?: string;
    /**
     * Optional list of individual error details
     */
    errors?: Array<ErrorDetail> | null;
    /**
     * A URI reference that identifies the specific occurrence of the problem.
     */
    instance?: string;
    /**
     * HTTP status code
     */
    status?: number;
    /**
     * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
     */
    title?: string;
    /**
     * A URI reference to human-readable documentation for the error.
     */
    type?: string;
};

export type GetAccountsResponseBodyWritable = {
    accounts: Array<AccountDto> | null;
};

export type GetChatByIdResponseBodyWritable = {
    chat: ChatDto;
};

export type GetChatSummariesResponseBodyWritable = {
    summaries: Array<ChatSummaryDto> | null;
};

export type GetChatSummaryResponseBodyWritable = {
    summary: ChatSummaryDto;
};

export type GetChatsResponseBodyWritable = {
    chats: Array<ChatDto> | null;
};

export type GetImportsResponseBodyWritable = {
    imports: Array<ImportDto> | null;
};

export type GetMessagesByChatIdResponseBodyWritable = {
    messages: Array<MessageDto> | null;
    page: number;
    pageCount: number;
    pageSize: number;
    total: number;
};

export type GetMessagesResponseBodyWritable = {
    messages: Array<MessageDto> | null;
};

export type GetApiFacebookAccountsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/facebook/accounts';
};

export type GetApiFacebookAccountsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetApiFacebookAccountsError = GetApiFacebookAccountsErrors[keyof GetApiFacebookAccountsErrors];

export type GetApiFacebookAccountsResponses = {
    /**
     * OK
     */
    200: GetAccountsResponseBody;
};

export type GetApiFacebookAccountsResponse = GetApiFacebookAccountsResponses[keyof GetApiFacebookAccountsResponses];

export type GetApiFacebookChatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/facebook/chats';
};

export type GetApiFacebookChatsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetApiFacebookChatsError = GetApiFacebookChatsErrors[keyof GetApiFacebookChatsErrors];

export type GetApiFacebookChatsResponses = {
    /**
     * OK
     */
    200: GetChatsResponseBody;
};

export type GetApiFacebookChatsResponse = GetApiFacebookChatsResponses[keyof GetApiFacebookChatsResponses];

export type GetApiFacebookChatsSummariesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/facebook/chats/summaries';
};

export type GetApiFacebookChatsSummariesErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetApiFacebookChatsSummariesError = GetApiFacebookChatsSummariesErrors[keyof GetApiFacebookChatsSummariesErrors];

export type GetApiFacebookChatsSummariesResponses = {
    /**
     * OK
     */
    200: GetChatSummariesResponseBody;
};

export type GetApiFacebookChatsSummariesResponse = GetApiFacebookChatsSummariesResponses[keyof GetApiFacebookChatsSummariesResponses];

export type GetApiFacebookChatsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/facebook/chats/{id}';
};

export type GetApiFacebookChatsByIdErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetApiFacebookChatsByIdError = GetApiFacebookChatsByIdErrors[keyof GetApiFacebookChatsByIdErrors];

export type GetApiFacebookChatsByIdResponses = {
    /**
     * OK
     */
    200: GetChatByIdResponseBody;
};

export type GetApiFacebookChatsByIdResponse = GetApiFacebookChatsByIdResponses[keyof GetApiFacebookChatsByIdResponses];

export type GetApiFacebookChatsByIdMessagesData = {
    body?: never;
    path: {
        id: string;
    };
    query?: {
        page?: number;
        pageSize?: number;
    };
    url: '/api/facebook/chats/{id}/messages';
};

export type GetApiFacebookChatsByIdMessagesErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetApiFacebookChatsByIdMessagesError = GetApiFacebookChatsByIdMessagesErrors[keyof GetApiFacebookChatsByIdMessagesErrors];

export type GetApiFacebookChatsByIdMessagesResponses = {
    /**
     * OK
     */
    200: GetMessagesByChatIdResponseBody;
};

export type GetApiFacebookChatsByIdMessagesResponse = GetApiFacebookChatsByIdMessagesResponses[keyof GetApiFacebookChatsByIdMessagesResponses];

export type GetApiFacebookChatsByIdSummaryData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/facebook/chats/{id}/summary';
};

export type GetApiFacebookChatsByIdSummaryErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetApiFacebookChatsByIdSummaryError = GetApiFacebookChatsByIdSummaryErrors[keyof GetApiFacebookChatsByIdSummaryErrors];

export type GetApiFacebookChatsByIdSummaryResponses = {
    /**
     * OK
     */
    200: GetChatSummaryResponseBody;
};

export type GetApiFacebookChatsByIdSummaryResponse = GetApiFacebookChatsByIdSummaryResponses[keyof GetApiFacebookChatsByIdSummaryResponses];

export type GetApiFacebookImportsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/facebook/imports';
};

export type GetApiFacebookImportsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetApiFacebookImportsError = GetApiFacebookImportsErrors[keyof GetApiFacebookImportsErrors];

export type GetApiFacebookImportsResponses = {
    /**
     * OK
     */
    200: GetImportsResponseBody;
};

export type GetApiFacebookImportsResponse = GetApiFacebookImportsResponses[keyof GetApiFacebookImportsResponses];

export type PostApiFacebookImportsData = {
    body?: {
        file: Blob | File;
        name: string;
    };
    path?: never;
    query?: never;
    url: '/api/facebook/imports';
};

export type PostApiFacebookImportsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type PostApiFacebookImportsError = PostApiFacebookImportsErrors[keyof PostApiFacebookImportsErrors];

export type PostApiFacebookImportsResponses = {
    /**
     * OK
     */
    200: CreateImportResponseBody;
};

export type PostApiFacebookImportsResponse = PostApiFacebookImportsResponses[keyof PostApiFacebookImportsResponses];

export type GetApiFacebookMessagesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/facebook/messages';
};

export type GetApiFacebookMessagesErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetApiFacebookMessagesError = GetApiFacebookMessagesErrors[keyof GetApiFacebookMessagesErrors];

export type GetApiFacebookMessagesResponses = {
    /**
     * OK
     */
    200: GetMessagesResponseBody;
};

export type GetApiFacebookMessagesResponse = GetApiFacebookMessagesResponses[keyof GetApiFacebookMessagesResponses];
