name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Nx CI & Build
        uses: MansaGroup/nrwl-nx-action@v2
        with:
          targets: lint,test,build
          workingDirectory: ./
          all: 'true'
          parallel: 'true'
          nxCloud: 'true'
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: dist/
